### ISSUE TITLE
Link google colab

### ISSUE THREAD

**Issue by chanelcolgate** [chanelcolgate/hydroelectric-project#3]
[15 RNN Stock Price](https://colab.research.google.com/drive/1TY6odKKbv4uJ3A_QKgkQ0oTugjLtzydL?usp=sharing)
[Gia dien du bao.ipynb](https://colab.research.google.com/drive/1eyxBhsduKYhHElvimFi-mgZpi7xELc-q?usp=sharing)
[SMP_2021_forecast](https://colab.research.google.com/drive/1XOdnz7iS9x-XrIJIWlxzW5BxkWVxukWd?usp=sharing)

**Comment by PhanDuyLinh** [comment]
https://colab.research.google.com/drive/1XOdnz7iS9x-XrIJIWlxzW5BxkWVxukWd?usp=sharing

**Comment by chanelcolgate** [comment]
[Online_Learning](https://colab.research.google.com/drive/1Ht-QgR8HmnTLUv0xNrRlHEThxKIRqdxn?usp=sharing)
